Goulding/krak/aptops v2 examples
LayerZero-Labs/devtools pull request #1080
Opened 2024-11-25 17:48 UTC by ryandgoulding

2025-01-07 22:09 UTC, St0rmBr3w requested changes
@AlexanderLiteplo did you mean to push these core dependencies up?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/cli/operations/evm-wire.ts
> +    reqArgs = ['lz_config']
Why `--lz-config` instead of `--oapp-config` like everywhere else?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-extensible-cli/cli/AptosEVMCli.ts
> +    args: any
Any time I see `any` in typescript I get a little nervous.  Is there any way to restrict the typing on this?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/endpoint.ts
> +        return result[0] as string
What if the send library is not defined (i.e., result.length = 0)?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/endpoint.ts
> +            return [result[0] as string, result[1] as boolean]
similar to above comment

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +// todo: implement connection builder that reads form yaml and fills in config with movement stuff if needed
Why yaml?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +export function getChain(fullnode: string): string {
What if a non-sensical string is used for `fullnode`?  Costs very little to be careful.

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +    [Network.TESTNET]: 'https://indexer.testnet.porto.movementnetwork.xyz/v1/graphql',
Why are we relying on an indexer here?  I am concerned that we may overburden the endpoint.

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/msgLib.ts
> +export class MsgLib {
Why did you go with your own abstraction rather than re-use the one already in monorepo?

https://github.com/LayerZero-Labs/monorepo/blob/main/packages/layerzero-v2/aptos/movevm-sdk/src/modules/uln302.ts

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/sdk/oapp.ts
> +export class OAPP {
NIT:  I would prefer `OApp`, but not a big deal.

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/tasks/evm/utils/types.ts
> +export const ZEROADDRESS_EVM = '0x0000000000000000000000000000000000000000'
You are already importing ethers, so why not use https://github.com/ethers-io/ethers.js/blob/v5.7/packages/constants/src.ts/addresses.ts#L1?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/tasks/evm/wire-evm.ts
> + * @description Handles wiring of EVM contracts with the Aptos OApp
So you recreated the EVM transaction generation for only the EVM <> Aptos paths?  My concern is what about other VMs, such as Solana?  At least a few of our day 1 launch partners already have Solana deployments.

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/tasks/evm/wire-evm.ts
> +    const privateKey = env.parsed.EVM_PRIVATE_KEY
What about a mnemonic?  The rest of our configs will use either mnemonic or pk, so I just want to prevent confusion if at all possible.

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/tasks/evm/wire-evm.ts
> +    // TxTypeEidMapping.setReceiveLibraryTimeout = await createSetReceiveLibraryTimeoutTransactions(
Any reason this is commented out?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/tasks/evm/wire/transactionExecutor.ts
> +            nonce: await signer.getTransactionCount(),
This is prone to nonce conflict if there is more than one transaction for a given eid.  If this is not a realistic use case, then no worries.  Otherwise, consider reading it into a map and incrementing as you go.

2025-01-10 00:47 UTC, ryandgoulding commented on packages/devtools-move/tasks/move/build.ts
> +    const cmd = 'aptos'
Is there a specific assumed aptos version?  Should we check for that version?

2025-01-10 00:47 UTC, ryandgoulding commented on packages/oft-evm/artifacts/OFT.sol/OFT.json
>      "transferFrom(address,address,uint256)": "23b872dd",
Why did this file change?  Probably should not have?

2025-01-10 18:42 UTC, DanL0 commented on examples/oft-move-adapter/README.md
> +First modify deploy-move/OFTAdpaterInitParams.ts and replace the oftMetadata with your desired values:
typo - OFTAdpater

2025-01-10 18:42 UTC, DanL0 commented on examples/oft-move-adapter/README.md
> +For deploy script tags use:
missing content, doesn't say what to use

2025-01-10 18:42 UTC, DanL0 commented on examples/oft-move-adapter/contracts/mocks/MyOFTMock.sol
MyOFTMock is unnecessary in the oft-move-adapter because OFT liquidity should come from Aptos side (because this is Adapter example, token already exists on A[tps). Therefore minting any EVM OFTs supply in any setup with adapter isn't recommended and might encourage users to follow incorrect flow.

2025-01-10 18:42 UTC, DanL0 commented on examples/oft-move-adapter/deploy/MyEVMOFT.ts
> +const contractName = 'MyOFT'
another reason why MyOFTMock should be removed - it's not even used - here MyOFT is used not MyOFTMock

and that's correct in deploy script it should be MyOFT that's deployed not the mock, mock should be removed

2025-01-10 19:16 UTC, AlexanderLiteplo commented on packages/devtools-extensible-cli/cli/AptosEVMCli.ts
> +    async execute(_callFromInheritance: boolean = false) {
@shankars99

2025-01-10 19:17 UTC, AlexanderLiteplo commented on packages/devtools-extensible-cli/cli/AptosEVMCli.ts
> +    args: any
@shankars99

2025-01-10 22:24 UTC, AlexanderLiteplo commented on examples/oft-move-adapter/README.md
> +For deploy script tags use:
fixed in a new update! good catch though :)

2025-01-10 22:25 UTC, AlexanderLiteplo commented on examples/oft-move-adapter/contracts/mocks/MyOFTMock.sol
good point!

2025-01-10 22:25 UTC, AlexanderLiteplo commented on examples/oft-move-adapter/contracts/mocks/MyOFTMock.sol
@St0rmBr3w can you confirm?

2025-01-10 22:53 UTC, St0rmBr3w commented on examples/oft-move-adapter/contracts/mocks/MyOFTMock.sol
This is somewhat true, although in practice no one should deploy the MyOFTMock in general on mainnet. 

But yes, you should flag in README that the Aptos Adapter is meant for tokens that DO NOT already exist on EVM.

Liquidity should only come from Aptos outbound to OFTs. No existing liquidity should already exist on other EVMs.

2025-01-11 14:03 UTC, shankars99 commented on packages/devtools-extensible-cli/cli/AptosEVMCli.ts
> +    async execute(_callFromInheritance: boolean = false) {
that was a used variable but isnt now. removed it

2025-01-11 14:03 UTC, shankars99 commented on packages/devtools-move/cli/operations/evm-wire.ts
> +    reqArgs = ['lz_config']
just a variable - changing it

2025-01-11 14:17 UTC, shankars99 commented on packages/devtools-extensible-cli/cli/AptosEVMCli.ts
> +    args: any
`args: any` => `(method) ArgumentParser.parse_args(args?: string[], ns?: Namespace | object): any`  
is generated by the parser which loads an object with all the flags that are passed via the command line into it - these flags are defined in the sdk's operations and every operation like wire have required flags that are checked - and since they are asserted then we can assume they exist in the any  

```
this.validateArgs(exec_op.requiredArgs)
    for (const arg of args) {
            if (!this.args[arg]) {
            // parser loads flags with `_` instead of `-` so: `--oapp-config` would be loaded as `oapp_config`
                missingArgs.push(`--${arg.replace('_', '-')}=<value>`) 
                isValid = false
            }
        }
        if (!isValid) {
            throw new Error(`The following args are required: ${missingArgs.join(', ')}\n\n`)
        }
```
    
and you pass in the list of required args via 

```    
    class EVMWireOperation implements INewOperation {
        vm = 'evm'
        operation = 'wire'
        description = 'Wire EVM contracts'
        reqArgs = ['oapp_config']
    
        async impl(args: any): Promise<void> {
            await wireEvm(args)
        }
}
```

and you also specify what the arg is 

```
{
addArgs = [
      {
            name: '--oapp-config',
            arg: {
                help: 'path to the layerzeroconfig file',
                required: false,
            },
      },
     ...
]
```

2025-01-11 14:19 UTC, shankars99 commented on packages/devtools-move/tasks/evm/utils/types.ts
> +export const ZEROADDRESS_EVM = '0x0000000000000000000000000000000000000000'
bruh.mp4

lol yeah changing that did not know this existed

2025-01-11 15:41 UTC, shankars99 commented on packages/devtools-move/tasks/evm/wire/transactionExecutor.ts
> +            nonce: await signer.getTransactionCount(),
yep this is handled in line 101 of the same file - will add a comment later at line 70 about this

`tx.nonce = accountEidMap[eid].nonce++`

2025-01-11 15:42 UTC, shankars99 commented on packages/devtools-move/tasks/evm/wire-evm.ts
> +    // TxTypeEidMapping.setReceiveLibraryTimeout = await createSetReceiveLibraryTimeoutTransactions(
i uh don't really know - prolly was to get through the wiring faster and i just forgot - will be uncommenting it

2025-01-11 15:43 UTC, shankars99 commented on packages/devtools-move/tasks/evm/wire-evm.ts
> +    const privateKey = env.parsed.EVM_PRIVATE_KEY
oh - will add that in

2025-01-11 15:43 UTC, shankars99 commented on packages/devtools-move/tasks/evm/wire-evm.ts
> + * @description Handles wiring of EVM contracts with the Aptos OApp
lemme add in a base-x parser rq

2025-01-11 16:02 UTC, shankars99 commented on packages/devtools-move/tasks/evm/wire-evm.ts
> + * @description Handles wiring of EVM contracts with the Aptos OApp
just did https://github.com/LayerZero-Labs/devtools/commit/c477ada26aebc8b6172316151688bc51c597feb0

@AlexanderLiteplo you can use this in aptos wire . i will be adding it to evm wire later today

2025-01-12 15:25 UTC, shankars99 commented on packages/devtools-move/sdk/endpoint.ts
> +        return result[0] as string
@AlexanderLiteplo

2025-01-12 15:25 UTC, shankars99 commented on packages/devtools-move/sdk/endpoint.ts
> +            return [result[0] as string, result[1] as boolean]
@AlexanderLiteplo

2025-01-12 15:44 UTC, shankars99 commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +// todo: implement connection builder that reads form yaml and fills in config with movement stuff if needed
to use aptos (even for building contracts) you need to run aptos init which creates a yaml file with the rpc url, account address, public key, (private key lol) - which aptos calls under the hood for all transactions, building, and deploying. so we figured we might as well just use it

2025-01-12 15:45 UTC, shankars99 commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +export function getChain(fullnode: string): string {
i think the value there is yanked from aptos config which is pre validated

2025-01-12 15:45 UTC, shankars99 commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +    [Network.TESTNET]: 'https://indexer.testnet.porto.movementnetwork.xyz/v1/graphql',
@AlexanderLiteplo if he knows what that is

2025-01-12 15:45 UTC, shankars99 commented on packages/devtools-move/sdk/msgLib.ts
> +export class MsgLib {
@AlexanderLiteplo

2025-01-12 15:46 UTC, shankars99 commented on packages/devtools-move/tasks/evm/wire-evm.ts
> +    // TxTypeEidMapping.setReceiveLibraryTimeout = await createSetReceiveLibraryTimeoutTransactions(
done!

2025-01-12 15:46 UTC, shankars99 commented on packages/devtools-move/tasks/move/build.ts
> +    const cmd = 'aptos'
hmm im not sure about this. i programmed the build and deploy so if there is one (@AlexanderLiteplo  do you know?) i can add in flags for it

2025-01-13 01:17 UTC, St0rmBr3w commented on tests-user/tests/create-lz-oapp.bats
> +}
if we're not gonna have the coin example either, you'll probably need to update the unit tests here

2025-01-28 18:26 UTC, AlexanderLiteplo commented on packages/devtools-move/tasks/move/build.ts
> +    const cmd = 'aptos'
We are currently using 6.0.1 so I'm just going to check if it's that or greater.

2025-01-28 18:34 UTC, AlexanderLiteplo commented on packages/devtools-move/tasks/evm/wire-evm.ts
> +    const privateKey = env.parsed.EVM_PRIVATE_KEY
@shankars99 did you do this?

2025-01-28 19:39 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/endpoint.ts
> +        return result[0] as string
never returns undefined

2025-01-28 19:39 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/endpoint.ts
> +            return [result[0] as string, result[1] as boolean]
rpc requrest will error if undefined

2025-01-28 19:40 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +// todo: implement connection builder that reads form yaml and fills in config with movement stuff if needed
this week i'm updating this to use env and get rid of yaml completely

2025-01-28 19:42 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +    [Network.TESTNET]: 'https://indexer.testnet.porto.movementnetwork.xyz/v1/graphql',
to connect to movement we need to specify and indexer, however this code is not currently in use and was built in prep for movement and will eventually be overwritten

2025-01-28 19:51 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/msgLib.ts
> +export class MsgLib {
didn't know that existed. at this point its been thoroughly tested though so not going to fix

2025-01-28 19:56 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/oapp.ts
> +export class OAPP {
old abstraction - deleted

2025-01-28 19:59 UTC, AlexanderLiteplo commented on packages/devtools-move/sdk/moveVMConnectionBuilder.ts
> +export function getChain(fullnode: string): string {
pulled from aptos config so will always be the same. for movement and initia update we will trashcan this method and rely on .env and move.layerzero.config for chain

2025-02-12 02:40 UTC, closed without merging