Update devtools-ton
LayerZero-Labs/devtools pull request #1129
Opened 2024-12-12 21:30 UTC by KaiStevenson

2024-12-12 21:59 UTC, KaiStevenson commented
@SocketSecurity ignore npm/@layerzerolabs/lz-ton-sdk-v2@3.0.24-ton.0

2024-12-12 22:31 UTC, yargo13 requested changes

2024-12-12 22:31 UTC, yargo13 commented on packages/devtools-ton/jest.config.ts
> +    testTimeout: 250000,
Bring this back to original value

2024-12-12 22:31 UTC, yargo13 commented on packages/devtools-ton/CHANGELOG.md
> +- Added new tests
Don't need to do it manually, changeset will do it

2024-12-12 22:31 UTC, yargo13 commented on packages/devtools-ton/package.json
> +  "private": true,
Don't need to update manually, and shouldn't be private

2024-12-12 22:31 UTC, yargo13 commented on packages/devtools-ton/package.json
> +    "access": "restricted"
This can be public

2024-12-12 22:31 UTC, yargo13 commented on packages/devtools-ton/package.json
> +    "@layerzerolabs/io-devtools": "~0.1.14",
Check that all other places have this updated as well

2024-12-13 00:33 UTC, yargo13 approved these changes

2024-12-13 00:34 UTC, merged