🗞️ Adding in Default Colors to print outs
LayerZero-Labs/devtools pull request #381
Opened 2024-02-09 19:17 UTC by sirarthurmoney

### In thi PR

- Adding in default colors

Screenshots:
 
<img width="301" alt="Screenshot 2024-02-09 at 11 10 14 AM" src="https://github.com/LayerZero-Labs/devtools/assets/95722332/7f52cffa-c201-465a-a032-17d650b819c8">
<img width="1733" alt="Screenshot 2024-02-09 at 11 13 39 AM" src="https://github.com/LayerZero-Labs/devtools/assets/95722332/be717b36-2d78-4144-a466-7337a1dadfee">
<img width="712" alt="Screenshot 2024-02-09 at 11 14 03 AM" src="https://github.com/LayerZero-Labs/devtools/assets/95722332/6f43e867-6fd4-4e7c-a960-bf5d82e56d9c">
<img width="440" alt="Screenshot 2024-02-09 at 11 14 44 AM" src="https://github.com/LayerZero-Labs/devtools/assets/95722332/3ae8da17-89a2-4930-b177-395efe1afd2d">

2024-02-09 19:26 UTC, janjakubnanista requested changes

2024-02-09 19:26 UTC, janjakubnanista commented on packages/io-devtools/src/stdio/printer.ts
> + * @param valueColor - color of values in table (DEFAULT: MAGENTA)
Here the JSDoc should be something like:

```typescript
/**
 * @param {boolean} [center] ...
 * @param {Preprocess} [keyColor] ...
 */
```

The `[]` mean a param is optional and the `{}` denote the type

2024-02-09 19:26 UTC, janjakubnanista commented on packages/io-devtools/src/stdio/printer.ts
> + * @param falseColor
The same as above

2024-02-09 19:26 UTC, janjakubnanista commented on packages/ua-devtools-evm-hardhat/src/tasks/oapp/peers.get.ts
> +            `${printBoolean(undefined)} - Ignored`
Here you can also split it into several logs:

```typescript
console.log(printCrossTable(peerNetworkMatrix, ['from → to', ...points.map(({ networkName }) => networkName)], true))
console.log(`${printBoolean(true)} - Connected`)
console.log(`${printBoolean(false)} - Not Connected`)
console.log(`${printBoolean(undefined)} - Ignored `)
```

2024-02-09 19:32 UTC, janjakubnanista requested changes

2024-02-09 19:32 UTC, janjakubnanista commented on packages/io-devtools/src/stdio/printer.ts
> +
You can also do

```typescript
const colAligns = center 
  ? ['left', ...Array.from({ length: records.length }).fill('center')]
  : undefined
```

Or shorter:

```typescript
const colAligns = center 
  ? ['left', ...records.slice().fill('center')]
  : undefined
```

2024-02-09 19:37 UTC, sirarthurmoney commented on packages/io-devtools/src/stdio/printer.ts
> +
Yes there are better👍

2024-02-10 00:42 UTC, janjakubnanista approved these changes
📅🌮

2024-02-10 00:49 UTC, merged