Add workflow and fix typos
LayerZero-Labs/devtools pull request #479
Opened 2024-03-14 06:59 UTC by miles-six

I fix many typos and want to add workflow for codespell check to eliminate typos in the future.

I have added a relatively simple filtering file to exclude certain words. 

If you find it meaningful, you can modify the filtering conditions according to your needs.

The code quality is exceptionally high, so sincerely hope my PR can help make this repository more standardized.

2024-03-14 17:05 UTC, janjakubnanista commented
Hey @miles-six! Thanks for the PR!

Since this is a node-based codebase for most of it, I'd rather use the [cspell](https://www.npmjs.com/package/cspell) from NPM, that should be an easy change (that way you can add it to the root `devDependencies` and forget about `requirements.txt`).

The second change I'd make is to add the spellcheck to the existing [code check workflow](https://github.com/LayerZero-Labs/devtools/blob/main/.github/workflows/reusable-test.yaml#L22) as a separate step, no need to spin up a new workflow just for this one.

2024-03-14 18:27 UTC, janjakubnanista commented on packages/export-deployments/src/common/fs.test.ts
> -            expect(readFileSyncSafe('filename')).toEqual(E.left(new Error('borken')))
This one here is intentional, it's a broken _broken_

2024-03-14 18:27 UTC, janjakubnanista commented on packages/export-deployments/src/common/fs.test.ts
> -            expect(mkdirSafe('some/dir/name')).toEqual(E.left(new Error('borken')))
Same here

2024-03-14 18:27 UTC, janjakubnanista commented on packages/verify-contract/test/url.test.ts
> -        it.each([[''], ['borken url'], ['https://'], ['https:///'], ['scan.api']])(
Same here

2024-03-14 18:27 UTC, janjakubnanista commented on packages/export-deployments/src/common/fs.test.ts
> -                throw 'borken'
Same here

2024-03-15 02:34 UTC, miles-six commented
@janjakubnanista  Hey,sir,thanks for your response！
I'm not quite sure if what I'm doing is correct, but I would like to directly add the following modified code (I removed requirements.txt) to the end of .github/workflows/reusable-test.yaml. 

  # We'll collect the docker compose logs from all containers on failure
      - name: Store docker logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: ./logs

# here is I would add
    codespell:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the repository
          uses: actions/checkout@v4

        - name: pip cache
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip
            restore-keys: ${{ runner.os }}-pip-

        - name: Install prerequisites
          run: sudo pip install codespell==2.2.5

        - name: Spell check
          run: codespell --config=./.codespell/.codespellrc

If this is incorrect, could you please guide me on what I should do?

2024-03-16 07:59 UTC, miles-six commented
@janjakubnanista  I have integrate codespell to existing [code check workflow](https://github.com/LayerZero-Labs/devtools/blob/main/.github/workflows/reusable-test.yaml#L22),and deleate requirements.txt

2024-03-18 07:16 UTC, miles-six commented
Hey @janjakubnanista sir
maybe I need to add some words to words.txt to skip , but it should after approving can start code test

2024-03-18 16:26 UTC, janjakubnanista requested changes
Could you please use the node version of `cspell`? We don't want to be introducing python if it's not justified

2024-03-18 16:26 UTC, janjakubnanista commented on .codespell/wordlist.txt
> +crate
Please add _borken_ here as well, we actually use it :)

2024-03-18 16:26 UTC, janjakubnanista commented on .github/workflows/reusable-test.yaml
> +        run: codespell --config=./.codespell/.codespellrc
What I meant in my first was not to use the python version at all - use the node version so that we don't introduce new language to the stack please

2024-03-19 16:50 UTC, janjakubnanista commented on .github/workflows/reusable-test.yaml
> +        run: npm install -g cspell
You can replace this part with:

```yaml
      - name: Setup environment
        uses: ./.github/workflows/actions/setup-environment

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-dependencies
```

Then add the `cspell` dependency as `devDependency` to the root `package.json` (either add it manually and run `pnpm install` or run `pnpm add -W -D cspell`). Don't forget to run `nvm use` before installing anything to make sure your node version matches the `.nvmrc`!

2024-03-19 16:50 UTC, janjakubnanista commented on .cspell/cspell.json
> +  // words - list of words to be always considered correct
I think JSON does not support comments, please remove these

2024-03-19 16:52 UTC, janjakubnanista commented on .github/workflows/reusable-test.yaml
> +    runs-on: ubuntu-latest
Please also add `name: Check spelling` to make this job look pretty in the github actions UI

2024-03-20 05:52 UTC, miles-six commented
Hey @janjakubnanista  To avoid affecting the repository, I have set all the files in the ./ directory to be ignored. Additionally, for aesthetics and better management, I have moved the cspell settings to the package.json file.

2024-03-21 01:18 UTC, miles-six commented
@janjakubnanista If you need any configuration, please let me know at any time

2024-03-21 19:05 UTC, janjakubnanista requested changes
There are two more issues with the setup - if you could fix those please.

2024-03-22 02:08 UTC, miles-six commented on .github/workflows/reusable-test.yaml
> +        run: cspell "**/*" --config ./.cspell/cspell.json
yes, cspell CLI -  this command exit with error code not correct

2024-03-22 07:43 UTC, miles-six commented
After several hours of effort, I managed to reduce the number of Unknown words from 2000 to 40. 
1.Although these remaining 40 may appear to be typos, they are actually part of a specific function, so I did not directly modify them. I'm unsure whether I should add these words to the ignore list or add the file to the ignore list for this particular case.

2.In the cspell.json file, I added some filtering words, including proper nouns.

3.The filtered paths can also be seen in the cspell.json file.
<img width="917" alt="image" src="https://github.com/LayerZero-Labs/devtools/assets/66052478/65048493-53e8-47f8-a1e1-94868a34c0e4">

2024-03-25 16:51 UTC, janjakubnanista commented
@miles-six looks good, thanks! Could you just resolve the merge conflict in `pnpm-lock.yaml` (running `pnpm i` from root after hitting the conflict should do)? After that we can run the workflows and see what comes out

2024-03-26 03:11 UTC, miles-six commented
@janjakubnanista  I already resolved the merge conflict in pnpm-lock.yaml and runn pnpm i from root

2024-03-26 17:12 UTC, janjakubnanista requested changes
Small thing to make the workflow pass - check my comment above. Thanks!

2024-03-26 17:12 UTC, janjakubnanista commented on .github/workflows/reusable-test.yaml
> +        uses: ./.github/workflows/actions/setup-environment
[The workflow has unfortunately failed](https://github.com/LayerZero-Labs/devtools/actions/runs/8430221261/job/23116118945?pr=479) - the problem is that this job is missing the first step:

```yaml
steps:
  - name: Checkout repo
     uses: actions/checkout@v4
```

Once you put that one in you should be good and green!

2024-03-27 07:04 UTC, miles-six commented
@janjakubnanista  I'm not sure about the exact cause of the error in the previous commit. If possible, I would appreciate it if you could take over and make the necessary modifications directly.

2024-03-27 15:55 UTC, janjakubnanista commented
> @janjakubnanista I'm not sure about the exact cause of the error in the previous commit. If possible, I would appreciate it if you could take over and make the necessary modifications directly.

Oh you're just an inch away @miles-six! The problem is that `cspell` command is not available globally. You can just simply replace `cspell` with `pnpm cspell` in your workflow and the problem will be gone.

2024-03-31 13:30 UTC, miles-six commented
@janjakubnanista hope you can help me sincerely

2024-04-02 12:32 UTC, closed without merging