Add cspell workflow
LayerZero-Labs/devtools pull request #530
Opened 2024-04-02 13:08 UTC by miles-six

@janjakubnanista  I pull the latest code and try again #479

2024-04-03 16:53 UTC, janjakubnanista commented
@miles-six nice, thanks! Could you pls try rebasing again, I can't seem to be able to approve the workflow runs and github is not great at telling me why, it might be that the branch is just outdated

2024-04-03 17:03 UTC, miles-six commented
@janjakubnanista   
thanks sir, can you check it again?

2024-04-03 18:14 UTC, janjakubnanista requested changes

2024-04-03 18:14 UTC, janjakubnanista commented on .github/workflows/reusable-test.yaml
> +      run: pnpm cspell --config ./cspell.json
It looks like the indentation here is not correct, breaking the workflow https://github.com/LayerZero-Labs/devtools/actions/runs/8542631863

2024-04-03 18:22 UTC, miles-six commented
@janjakubnanista  resolved it

2024-04-03 18:40 UTC, miles-six commented
@janjakubnanista  I can run **cspell.** local successfully.I don't know why failed on github

2024-04-04 16:38 UTC, janjakubnanista commented
@miles-six I'll investigate the error in the CI - it's some real weirdness since `pnpm install` is trying to clone git repositories for some reason

2024-04-04 18:46 UTC, janjakubnanista commented
For some reason I was getting permission denied and don't have that much time to investigate - what I did was I pushed into [this branch](https://github.com/LayerZero-Labs/devtools/tree/miles-six/main) - I can either recreate your PR or you can fetch & hard reset your branch to this one then all should be good

2024-04-04 19:00 UTC, janjakubnanista commented
There still seems to be an issue with the command - I think it might need to be changed to `cspell lint`:

<img width="613" alt="Screenshot 2024-04-04 at 11 59 37 AM" src="https://github.com/LayerZero-Labs/devtools/assets/1451480/4473e527-4b4c-4a91-adf6-5b9384ead135">

2024-04-04 19:00 UTC, miles-six commented
> For some reason I was getting permission denied and don't have that much time to investigate - what I did was I pushed into [this branch](https://github.com/LayerZero-Labs/devtools/tree/miles-six/main) - I can either recreate your PR or you can fetch & hard reset your branch to this one then all should be good

Ok sir.Just do it your way. Thanks

2024-04-06 15:40 UTC, miles-six commented
@janjakubnanista  I change to cspell lint .

2024-04-09 17:44 UTC, janjakubnanista commented
@miles-six I have some high-priority things that I need to tend to, I will come back to you on this one in a bit

2024-04-23 17:05 UTC, miles-six commented
Yes. Waiting for it

2024-05-23 20:20 UTC, hadifalahi4142 commented
this project can a grow now

2024-07-18 19:56 UTC, closed without merging

2024-07-18 19:57 UTC, TRileySchwarz commented
Closed for now, will reprioritize this as needed.