🧹 Adding logging to configureSendConfig
LayerZero-Labs/devtools pull request #640
Opened 2024-06-12 23:43 UTC by ravinagill15

## In this PR:
- Added logging to `configureReceiveLibraries` in `ua-devtools > src > oapp > config.ts`

2024-06-13 00:08 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                    )
This is the change , along with the other log above (the rest of the function was just indented)

2024-06-13 00:08 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                        `Set Uln configuration ${updatedConfigListCsv} for ${formatOmniVector({ from, to })}`
This is the change , along with the other log above (the rest of the function was just indented)

2024-06-13 15:37 UTC, ravinagill15 reviewed
The changes highlighted by github are mostly due to indentation -- i have commented below the actual changes

2024-06-13 15:37 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                )
change 1

2024-06-13 15:37 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                        `Set executor configuration ${updatedConfigListCsv} for ${formatOmniVector({ from, to })}`
change 2

2024-06-13 15:37 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                    `Checked Uln configuration for ${formatOmniVector({ from, to })}: ${printBoolean(hasUlnConfig)}`
change 3

2024-06-13 15:37 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                    )
change 4

2024-06-13 15:37 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +        onSuccess: (logger) => logger.verbose(`${printBoolean(true)} Checked send configuration`),
change 5

2024-06-13 16:02 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +        onSuccess: (logger) => logger.verbose(`${printBoolean(true)} Checked send configuration`),
Noticed that when set to `verbose` this log doesn't appear in the test build run. When set to `info`, it appears.

Other logs within the actual logic appear, even with the verbose flag, so I can leave those as is, but should I change these `onStart` and `onSuccess` logs to use `info`?

2024-06-13 16:04 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                )
Despite[ this test ](https://github.com/LayerZero-Labs/devtools/blob/aae5fa2cd7a206968e46857a4e592000d5377db3/tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts#L757-L767) having a `config.sendConfig.executorConfig`, this log doesn't appear in the test build run. Perhaps I am checking the wrong test?

I would like to confirm this log and the `updatedConfigListCsv` log in the test build run before merging this PR

2024-06-13 20:43 UTC, ravinagill15 commented on packages/ua-devtools/src/oapp/config.ts
> +                )
The above is resolved -- once I expose the test networks on localhost, deploy and wire them with `--log-level verbose`, I am able to see these logs

2024-06-14 17:02 UTC, janjakubnanista requested changes

2024-06-14 17:02 UTC, janjakubnanista commented on .changeset/lemon-brooms-watch.md
> +Added logging to configureReceiveConfig
I think this might be a misrebase

2024-06-19 17:25 UTC, janjakubnanista approved these changes

2024-06-19 17:25 UTC, merged