Adding in OFTAdapter to create-lz-oapp
LayerZero-Labs/devtools pull request #713
Opened 2024-07-17 21:12 UTC by sirarthurmoney

In this PR:

- Adding in the ability for create-lz-app to generate OFTAdapter

2024-07-17 22:23 UTC, janjakubnanista approved these changes

2024-07-17 23:38 UTC, janjakubnanista approved these changes

2024-07-18 16:45 UTC, ryandgoulding commented on examples/oft-adapter/contracts/MyOFTAdapter.sol
> +import { OFTAdapter } from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFTAdapter.sol";
Use the ones in `@layerzerolabs/oft-evm` instead.

2024-07-18 20:07 UTC, TRileySchwarz approved these changes

2024-07-18 22:50 UTC, janjakubnanista approved these changes

2024-07-18 22:54 UTC, ryandgoulding approved these changes

2024-07-18 22:56 UTC, ryandgoulding requested changes

2024-07-18 22:56 UTC, ryandgoulding commented on examples/oft-adapter/test/foundry/MyOFTAdapter.t.sol
> +import { OFTComposeMsgCodec } from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTComposeMsgCodec.sol";
these need to be changed

2024-07-18 22:56 UTC, ryandgoulding commented on examples/oft-adapter/test/mocks/OFTAdapterMock.sol
> +import { OFTAdapter } from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFTAdapter.sol";
and this.

2024-07-18 22:56 UTC, ryandgoulding commented on examples/oft-adapter/test/mocks/OFTMock.sol
> +import { SendParam } from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFTCore.sol";
and these

2024-07-18 22:56 UTC, ryandgoulding commented on examples/oft-adapter/contracts/MyOFT.sol
> +import { OFT } from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFT.sol";
and this

2024-07-18 22:56 UTC, ryandgoulding commented on examples/oft-adapter/contracts/MyOFTAdapter.sol
> +import { OFTAdapter } from "@layerzerolabs/oft-evm/contracts/OFTAdapter.sol";
and this.

2024-07-18 22:56 UTC, ryandgoulding commented on examples/oft-adapter/contracts/mocks/MyOFTMock.sol
> +import { OFT } from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/OFT.sol";
and this.

2024-07-18 23:18 UTC, ryandgoulding approved these changes

2024-07-19 14:10 UTC, ryandgoulding approved these changes

2024-07-19 14:10 UTC, merged