🗞️ Migrate the OApp standard into devTools
LayerZero-Labs/devtools pull request #744
Opened 2024-07-22 23:08 UTC by TRileySchwarz

2024-07-23 20:29 UTC, janjakubnanista requested changes
Tiny tiny changes

2024-07-23 20:29 UTC, janjakubnanista commented on packages/oapp-evm/.gitignore
> +out
Drop this if you still have some committing energy

2024-07-23 20:29 UTC, janjakubnanista commented on packages/oapp-evm/foundry.toml
> +optimizer_runs = 20_000
You can speed up the build by removing this or setting it to like 200 - we are not deploying these directly so having the optimizer here does not matter at all

2024-07-23 20:29 UTC, janjakubnanista commented on packages/oapp-evm/turbo.json
> +        "out/**",
These can be dropped along with the `hh-cache`

2024-07-23 20:29 UTC, janjakubnanista commented on packages/oapp-evm/turbo.json
> +        "node_modules/**"
This as well, `node_modules` is mos def not an output for the build task

2024-07-23 20:44 UTC, ryandgoulding commented on packages/oapp-evm/package.json
> +    "solidity-bytes-utils": "^0.8.0"
grab this from toolbox-foundry instead.  can use this in foundry.toml:

```
'solidity-bytes-utils/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/solidity-bytes-utils/',
```

2024-07-23 20:44 UTC, ryandgoulding commented on packages/oapp-evm/package.json
> +    "solidity-bytes-utils": "^0.8.0"
drops this

2024-07-23 23:21 UTC, janjakubnanista approved these changes

2024-07-23 23:40 UTC, merged

2024-10-01 11:53 UTC, Maliksb11 commented
ok

2024-10-21 19:54 UTC, Maliksb11 commented
ok